extensions:
  - proj_flow.ext.python
  - proj_flow.ext.github
  - proj_flow.ext.re_structured_changelog
  - proj_flow.minimal.ext.bug_report
  - proj_flow.minimal.ext.versions

entry:
  build: [ Build ]
  install: [ Install ]
  docs: [ RTD ]
  verify: [ Build, Check Twine ]
  refresh: [ Install, Build, RTD, Check Twine ]

version-updates:
  schema/test-runner.yaml: tags/v$VERSION/
